# coding: utf-8

"""
    CPT Zip API

    CPT Bulk Zip API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datalabs@ama-assn.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from org.ama.client.api.CPTAPI_Zip.files_api import FilesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = org.ama.client.api.CPTAPI_Zip.files_api.FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_files(self):
        """Test case for get_files

        Zip archive of the CPT standard distribution data files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
