# coding: utf-8

"""
    CPT Zip API

    CPT Bulk Zip API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datalabs@ama-assn.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.org.ama.client.model.CPTAPI_Zip.release import Release  # noqa: E501
from openapi_client.rest import ApiException


class TestRelease(unittest.TestCase):
    """Release unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelease(self):
        """Test Release"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.release.Release()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
