'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { ArrowLeft, ArrowRight, RefreshCw, Lock } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

interface LivePreviewProps {
    initialUrl?: string;
}

/**
 * A placeholder component that sets up the UI for a live preview of a web page,
 * likely generated by an AI agent. It includes a styled iframe and placeholder controls.
 */
const LivePreview: React.FC<LivePreviewProps> = ({ initialUrl = 'about:blank' }) => {
  const [iframeUrl, setIframeUrl] = useState(initialUrl);
  const [inputUrl, setInputUrl] = useState(initialUrl);

  const handleNavigate = (e: React.FormEvent) => {
    e.preventDefault();
    setIframeUrl(inputUrl);
  };

  return (
    <div className="h-full flex flex-col bg-secondary/80 border border-border/60 rounded-lg overflow-hidden glass-morphism">
      {/* Toolbar */}
      <div className="flex items-center gap-2 p-2 bg-secondary border-b border-border/60 flex-shrink-0">
        <Button variant="ghost" size="icon" className="h-7 w-7">
          <ArrowLeft className="w-4 h-4" />
        </Button>
        <Button variant="ghost" size="icon" className="h-7 w-7">
          <ArrowRight className="w-4 h-4" />
        </Button>
        <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setIframeUrl(iframeUrl)}>
          <RefreshCw className="w-4 h-4" />
        </Button>
        <form onSubmit={handleNavigate} className="flex-grow relative">
            <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-3 h-3 text-muted-foreground" />
            <Input
                type="text"
                value={inputUrl}
                onChange={(e) => setInputUrl(e.target.value)}
                className="w-full h-8 bg-black/50 pl-8"
                placeholder="https://example.com"
            />
        </form>
      </div>

      {/* Iframe for content */}
      <div className="flex-grow bg-white">
        <iframe
          src={iframeUrl}
          title="Live Preview"
          className="w-full h-full border-0"
          sandbox="allow-scripts allow-same-origin"
        />
      </div>
    </div>
  );
};

export default LivePreview;
