# coding: utf-8

"""
    CPT Zip API

    CPT Bulk Zip API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datalabs@ama-assn.org
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="CPT Zip API",
    author_email="datalabs@ama-assn.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "CPT Zip API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    CPT Bulk Zip API  # noqa: E501
    """
)
