# coding: utf-8

# flake8: noqa
"""
    CPT Zip API

    CPT Bulk Zip API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: datalabs@ama-assn.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.org.ama.client.model.CPTAPI_Zip.release import Release
